string ACTION_NAME=/oni_vicon_player/JumpTo

int8 SOURCE_TIME = 0
int8 SOURCE_VICON_FRAME = 1
int8 SOURCE_DEPTH_SENSOR_FRAME = 2

float64 time
uint64 vicon_frame
uint64 depth_sensor_frame
int8 source
---
---
